<a href="https://colab.research.google.com/github/hyunchangyi/python101/blob/main/Ensemble2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 동전 앞/뒷면 예측 문제

문제를 간단히 하기 위해 항상 앞면(숫자 0)이 나오는 것으로 가정

각 분류기는 p > 0.5 확률로 0 예측하고 (1-p)확률로 1로 예측

## p가 작더라도 분류기가 많아지면 예측력이 높아질까?

In [6]:
import numpy as np

던져진 동전은 0.5 확률로 앞면(1), 0.5확률로 뒷면(0)이 나타남

In [7]:
E = lambda N: np.random.choice([0, 1], size=N, p=[0.5, 0.5])

In [8]:
E(2)

array([1, 1])

predictor는 prob 확률로 정확한 클래스(e)을 예측, 1-prob 확률로 틀린 클래스(1-e)을 예측

In [9]:
prob = 0.6
predictor = lambda e, prob: e if np.random.choice([False, True], p = [1 - prob, prob]) else 1 - e

In [10]:
NP = 10 # number of predictors

e = E(1)

preds = [predictor(e, 0.5) for i in range(NP)]

전체 predictors 의 예측 (다수결)

In [14]:
vote = 1 if sum(preds) >= 0.5 else 0

In [15]:
vote

1

In [16]:
vote == e

array([False])

In [ ]:
learner = lambda event, p: event if np.random.uniform

array([1, 0, 0, 0, 1, 0, 0, 1, 0, 1])

In [ ]:
# p 정확도인 n 개 분류기의 예측 시뮬레이션
classifiers = lambda n, p : (np.random.uniform(low=0, high=1, size=n) < p)

In [ ]:
# True는 정확히 맞춘 분류기
# 정확도가 높아질수록 정확히 맞춘 분류기 비중이 높아짐
classifiers(10, 0.8)

array([ True,  True, False, False, False,  True,  True,  True,  True,
        True])

정확도가 같은 여러 분류기의 과반투표로 예측한다면...

In [ ]:
n = 10
p = 0.8

if sum(classifiers(n, p))/n >= 0.5:
    print('0')
else:
    print('1')

0


같은 방식으로 여러번 예측을 수행했을때 정확도는?

In [ ]:
n = 10
p = 0.9
T = 1000

sum([sum(classifiers(n, p))/n >= 0.5 for i in range(T)])/T

1.0

정확도가 낮으면?

In [ ]:
n = 1000
p = 0.51
T = 1000

sum([sum(classifiers(n, p))/n >= 0.5 for i in range(T)])/T

0.775