<a href="https://colab.research.google.com/github/hyunchangyi/python2021/blob/main/python_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 주피터노트북


## 셀 타입

- 코드
- 마크다운/텍스트

## 셀 모드

- 편집
- 명령


## 셀 실행

- Shift + Enter 현재 셀 실행하고 아래 셀 선택
- Ctrl + Enter 현재 셀 실행하고 현재 셀 선택
- Alt + Enter (colab) 현재 셀 실행하고 아래에 새로운 코드 셀 생성

## 단축키
- 구글 코랩에서는 노트북 단축키를 사용자가 지정할 수 있으며, 일반적인 주피터노트북과 달리 셀 편집모드에서도 단축키를 통해 셀 잘라내기, 새로운 셀 생성 등 셀 편집이 가능

- '메뉴-도구-단축키'에서 설정
    - 셀 잘라내기 Ctrl + m, x
    - 셀 복사하기 Ctrl + m, c
    - 셀 붙이기 Ctrl + v
    - 셀 삭제 Ctrl + m, d
    - 위에 새로운 셀 삽입하기 Ctrl + m, a
    - 아래에 새로운 셀 삽입하기 Ctrl + m, b
    - 셀 타입 코드로 변환 Ctrl + m, y
    - 셀 타입 마크다운으로 변환 Ctrl + m, m
    - 실행 취소 Ctrl + m, z
    - 단축키 확인 Ctrl + m, x
    - 선택된 여러 셀 병합 Ctrl + Shift + m
    - 현재 커서 위치에서 셀 분할 Ctrl + m, -
    - 주석 설정/해제 Ctrl + /

# 기본 자료형

## 숫자, 참/거짓, 문자열

In [ ]:
1

1

In [ ]:
type(1)

int

In [ ]:
type(1.0)

float

In [ ]:
False, True

(False, True)

In [ ]:
type(False)

bool

In [ ]:
type('python')

str

In [ ]:
type("python")

str

In [ ]:
type('a')

str

In [ ]:
type("p")

str

In [ ]:
type('python'), type(.5)

(str, float)

In [ ]:
a = 5
b = (a == 5)
c = 'KOR'
print(a, b, c)

5 True KOR


- 더하기

In [ ]:
4 + 5

9

In [ ]:
'KOR' + '15'

'KOR15'

In [ ]:
'KOR' + 15

TypeError: ignored

- 수는 수끼리, 문자열은 문자열끼리 더할 수 있음
- 자료형 변경은 str(), float(), int() 등을 이용

In [ ]:
'KOR' + str(15)

'KOR15'

In [ ]:
type(str(15))

str

In [ ]:
float(str(15))

15.0

- bool 자료형에 사칙연산을 적용할 경우 False는 0, True는 1의 값을 갖는 것으로 처리됨

In [ ]:
4 + True

5

In [ ]:
4 + False

4

In [ ]:
4 * True

4

In [ ]:
4 * False

0

In [ ]:
int(True)

1

- 문자열 포맷 f-string

In [ ]:
a = 2
b = 'two'
print(a, b)

2 two


In [ ]:
print(f'{a} is {b}')

2 is two


In [ ]:
print(f'{a:.2f} is {b:}')

2.00 is two


In [ ]:
print(f'{b:} is {a:.2f}')

two is 2.00


In [ ]:
print(f'{b:} is {10000:,.2f}')

two is 10,000.00


- 문자열에서 공백 없애기

In [ ]:
" abc ".lstrip()

'abc '

In [ ]:
" abc ".rstrip()

' abc'

In [ ]:
" abc ".strip()

'abc'

In [ ]:
"abc".strip('a')

'bc'

## 리스트

In [ ]:
a = [1, 2, 3]
b = ['one', 'two', 'three']

In [ ]:
type(a)

list

In [ ]:
a * 2

[1, 2, 3, 1, 2, 3]

In [ ]:
b * 2

['one', 'two', 'three', 'one', 'two', 'three']

In [ ]:
a + b

[1, 2, 3, 'one', 'two', 'three']

In [ ]:
a + 5

TypeError: ignored

In [ ]:
a + 'four'

TypeError: ignored

- list에 숫자 또는 문자열을 더하는 연산이 정의되어 있지 않으므로 오류발생

In [ ]:
a + [5]

[1, 2, 3, 5]

In [ ]:
b.append('four')
print(b)

['one', 'two', 'three', 'four']


- 숫자로 이루어진 리스트의 각 항목에 숫자를 더하기 위해서는 list comprehension이나 for-loop 이용

In [ ]:
[i + 1 for i in a]

[2, 3, 4]

- 뒤에 다룰 넘파이 ndarray 자료형은 숫자형 자료 리스트처럼 생겼으나, 숫자 하나를 더할 수 있음

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

- 리스트에 있는 문자열을 특정 기호로 연결

In [ ]:
b

['one', 'two', 'three', 'four']

In [ ]:
':'.join(b)

'one:two:three:four'

- 파이썬 인덱스는 0부터 시작!! 

In [ ]:
a[0]

1

In [ ]:
a[0:2]

[1, 2]

- list의 마지막 항목의 인덱스는 -1

In [ ]:
a[-1]

3

In [ ]:
a = ['KOR', 'USA', 'CHN']
print(a[0], a[-1], a[:2], a[-2:])

KOR CHN ['KOR', 'USA'] ['USA', 'CHN']


- 주피터노트북에서 긴 리스트는 세로로 표시되지만, %pprint 명령어로 옵션 변경 가능,
- print() 명령어를 사용하면, 긴 리스트도 가로로 표시

In [ ]:
a * 4

['KOR',
 'USA',
 'CHN',
 'KOR',
 'USA',
 'CHN',
 'KOR',
 'USA',
 'CHN',
 'KOR',
 'USA',
 'CHN']

In [ ]:
print(a * 4)

['KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN']


In [ ]:
%pprint

Pretty printing has been turned OFF


In [ ]:
a * 4

['KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN']

- 문자열 리스트의 각 항목을 따옴표 없이 print()하기 위해 리스트이름 앞에 * 입력
- print()가 출력하는 각 항목 사이를 구분하기 위해 sep = '기호'를 지정
- print()가 마지막에 출력할 내용을 지정하기 위해 end = '기호'를 지정(기본은 '\n')

In [ ]:
print(a)

['KOR', 'USA', 'CHN']


In [ ]:
print(*a)

KOR USA CHN


In [ ]:
print(*a, sep = ', ')

KOR, USA, CHN


- list comprehension

In [ ]:
['KOR', 'USA', 'CHN'] - ['CHN', 'AUS']

TypeError: ignored

In [ ]:
[s for s in ['KOR', 'USA', 'CHN'] if s not in ['CHN', 'AUS']]

['KOR', 'USA']

- set() 이용

In [ ]:
set(['KOR', 'USA', 'CHN']), set(['CHN', 'AUS'])

({'USA', 'KOR', 'CHN'}, {'AUS', 'CHN'})

In [ ]:
set(['KOR', 'USA', 'CHN']) - set(['CHN', 'AUS'])

{'USA', 'KOR'}

In [ ]:
list(set(['KOR', 'USA', 'CHN']) - set(['CHN', 'AUS']))

['USA', 'KOR']

- 문자열 리스트 항목별로 문자열 더하기

In [ ]:
[s + ':g' for s in ['KOR', 'USA', 'CHN']]

['KOR:g', 'USA:g', 'CHN:g']

- 문자열은 각 캐릭터(123.../abc.../가나다... 등)로 구성된 리스트

In [ ]:
a = 'abcde'

In [ ]:
a[:3]

'abc'

In [ ]:
a[-2:]

'de'

In [ ]:
"가나다라마"[:2]

'가나'

- 이전 실행한 출력셀의 값 불러오기

In [ ]:
_

['KOR:g', 'USA:g', 'CHN:g']

In [ ]:
Out[71]

'abc'

In [ ]:
_63

NameError: ignored

- range()로 수 리스트 만들기
    - range(s, e, i): 처음 위치(생략시 0), 마지막 위치(리스트에 포함 안됨), 수 간격(생략시 1)
    - for-loop 등에서 주로 이용하며, 순서대로 해당하는 값만 필요하므로 실제 리스트를 생성하지 않음
        - 리스트 생성시 메모리 공간을 크게 차지할 수 있으므로 비효율적임
    - 리스트를 생성하기 위해서는 list() 함수 실행

In [ ]:
for i in range(5):  # range(0, 5, 1)
    print(i)

0
1
2
3
4


In [ ]:
for i in range(5, 0, -2):  # range(0, 5, 1)
    print(i)

5
3
1


In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## 딕셔너리

In [ ]:
iso = {'US':'USA', 'KR':'KOR', 'JP':'JPN', 'CN':'CHN'}

In [ ]:
kr_en = {'서울특별시':'SE', '경기도':'GG', '인청광역시':'IC'}

In [ ]:
iso['US']

'USA'

In [ ]:
iso['KR']

'KOR'

In [ ]:
iso.keys()

dict_keys(['US', 'KR', 'JP', 'CN'])

In [ ]:
iso.values()

dict_values(['USA', 'KOR', 'JPN', 'CHN'])

In [ ]:
iso['AU'] = 'AUS'

In [ ]:
iso

{'US': 'USA', 'KR': 'KOR', 'JP': 'JPN', 'CN': 'CHN', 'AU': 'AUS'}

- dict, zip으로 딕셔너리 만들기

In [ ]:
dict(zip(['한국', '미국', '일본'], ['KR', 'US', 'JP']))

{'한국': 'KR', '미국': 'US', '일본': 'JP'}

In [ ]:
import pandas as pd
countries = pd.Series(['South Korea', 'United States'])
print(countries)

0      South Korea
1    United States
dtype: object


In [ ]:
cdict = {'South Korea':'KR', 'United States':'US'}
countries.replace(cdict)

0    KR
1    US
dtype: object

## 터플

In [ ]:
a, b, c = 5, 10, 15

In [ ]:
print(a, b, c)

5 10 15


In [ ]:
a, b = b, a
print(a, b)

10 5


## 연습문제

- 아래 국가명 리스트와 연도 리스트를 이용하여 국가명_연도 문자열을 생성하라
- 아래 리스트와 인덱스를 이용하여 일본과 중국을 제외한 국가에 대해서만 국가명_연도 문자열을 생성하라

In [ ]:
countries = ['KOR', 'USA', 'JPN', 'CHN', 'AUS', 'MEX']
year = [17, 18, 19, 20]

- 아래 문자열 리스트에서 숫자를 나타내는 문자열만 선택하여 리스트를 생성하라(힌트, isnumeric()/isdigit(), strip() 이용)

In [ ]:
strings = ['KOR', '한국', '15', "True", '1000', '-5']

# 문법

- 파이썬에서 for loop, if 구문, 함수 정의시 indentation(스페이스 4개) 이용
    - 주피터노트북에서 tab은 스페이스 4개를 입력
- 코드작성의 자유도가 낮은 대신, 가독성이 매우 높아짐


```
<C>
if (i=1; i<=n; i++) {
  printf("%d\n", i);
}

<matlab>
for i = 1:n
    disp(i)
end

<python>
for i = range(1, n+1)
    disp(i)    
```

## definition

In [ ]:
def sum_two_numbers(a, b):
    return a + b

In [ ]:
sum_two_numbers(1, 2)

3

In [ ]:
def sum_three_numbers(a, b, c=4):
    return a + 2*b + c

In [ ]:
sum_three_numbers(1, 2, 0)

5

In [ ]:
sum_three_numbers(1, 2)

9

In [ ]:
sum_three_numbers(b=2, a=1)

9

In [ ]:
sum_two_numbers2 = lambda x, y: x + y

In [ ]:
sum_two_numbers2(1, 2)

3

## for-loop, if-else

In [ ]:
countries = ['KOR', 'USA', 'CHN']
for c in countries:
    if c == 'KOR':
        print(c, 'is my country.')
    else:
        print(c)

KOR is my country.
USA
CHN


## continue, break, pass

In [ ]:
for i in range(4):    # [0, 1, 2, 3]
    if i==2:
        continue
    else:
        print(f'{i} is not 2')


0 is not 2
1 is not 2
3 is not 2


In [ ]:
for i in range(4):    # [0, 1, 2, 3]
    if i==2:
        break
    else:
        print(f'{i} is not 2')


0 is not 2
1 is not 2


In [ ]:
if True:
else:
    print('False')

IndentationError: ignored

In [ ]:
if True:
    pass
else:
    print('False')

## list comprehension v. for-loop
- 앞 리스트에서 뒤 리스트에 속한 항목 제외하기

In [ ]:
[s for s in ['KOR', 'USA', 'CHN'] if s not in ['CHN','AUS']]

['KOR', 'USA']

In [ ]:
clist = []
for c in ['KOR', 'USA', 'CHN']:
    if c not in ['CHN', 'AUS']:
        clist = clist + [c] # clist.append(c)
clist

['KOR', 'USA']

# 라이브러리: numpy
- ndarray는 행(row)과 열(column) 보다 첫번째 차원, 두번째 차원, 세번째 차원 등으로 정의
- 필요한 경우 matrix 자료형을 사용할 수 있으나 활용도가 낮음
- ndarray자료형을 이용하여 일반적인 matrix연산을 모두 할 수 있음
- 2-dim ndarray에서 행(row)처럼 보이는 것은 첫번째 차원임

In [ ]:
import numpy
import numpy as np
print(numpy.sin(0), np.sin(0))

0.0 0.0


In [ ]:
print(sin(0))

NameError: ignored

In [ ]:
print(np.pi)

3.141592653589793


## 인덱스

- 특정 열(두번째 차원)에 접근하기 위해서는 콜론(:)을 첫번째 인덱스 자리에 입력

In [ ]:
a1 = np.array([[1, 2 ,3], [2, 3, 4]])

In [ ]:
a1[:, 0]

array([1, 2])

In [ ]:
a1[0, :]

array([1, 2, 3])

## 통계량 및 연산

In [ ]:
v = np.array([1, 2, 3])
print(v)

[1 2 3]


In [ ]:
type(v)

<class 'numpy.ndarray'>

In [ ]:
m = np.array([[1, 2], [3, 4]])
m

array([[1, 2],
       [3, 4]])

In [ ]:
print(v.mean(), v.std(), v.max())

2.0 0.816496580927726 3


In [ ]:
np.sin([0, np.pi / 2, np.pi])

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [ ]:
a = np.array([[1, 2], [3, 4]])

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
a[0,0] = -1

In [ ]:
a

array([[-1,  2],
       [ 3,  4]])

In [ ]:
a[0] = 0
a

array([[0, 0],
       [3, 4]])

In [ ]:
a[:, 1] = [5, 6]
print(a)

[[0 5]
 [3 6]]


In [ ]:
v1 = np.array([1, 2, 3])
v2 = np.array([-1, 0, 1])

In [ ]:
v1 + 1

array([2, 3, 4])

In [ ]:
v1 * 2

array([2, 4, 6])

In [ ]:
v1 ** 2

array([1, 4, 9])

In [ ]:
np.log(v1)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.exp(v1)

array([ 2.71828183,  7.3890561 , 20.08553692])

## dimension
- ndarray 간의 +, -, *, / 등 사칙연산은 elementwise이므로 모양이 서로 같아야함 

In [ ]:
v1.shape

(3,)

In [ ]:
a2 = np.array([[1, 2], [1, 3], [1, 4]])

In [ ]:
a2

array([[1, 2],
       [1, 3],
       [1, 4]])

In [ ]:
a2.shape

(3, 2)

In [ ]:
a1

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
a1 * a2

ValueError: ignored

In [ ]:
v1.shape, v2.shape

((3,), (3,))

In [ ]:
v1 + v2

array([0, 2, 4])

In [ ]:
v1 * v2

array([-1,  0,  3])

In [ ]:
v1.dot(v2)

2

In [ ]:
m

array([[1, 2],
       [3, 4]])

In [ ]:
m.T

array([[1, 3],
       [2, 4]])

In [ ]:
v = np.array([1, 0])
m.dot(v)

array([1, 3])

In [ ]:
v.dot(m)

array([1, 2])

In [ ]:
print('{} \n\n {}'.format(a1, a2.T))

[[1 2 3]
 [2 3 4]] 

 [[1 1 1]
 [2 3 4]]


In [ ]:
print(a1 * a2.T)

[[ 1  2  3]
 [ 4  9 16]]


## matrix operation

- numpy array로 생성된 객체는 ndarray 클래스의 메소드와 속성을 가짐
- transpose, dot product 등

In [ ]:
a1.dot(a2)

array([[ 6, 20],
       [ 9, 29]])

In [ ]:
np.dot(a1, a2)

array([[ 6, 20],
       [ 9, 29]])

In [ ]:
A = np.dot(a1, a2)
print(A)

[[ 6 20]
 [ 9 29]]


- 역행렬: numpy.linalg.inv() 함수 이용

In [ ]:
print(np.linalg.inv(a1.dot(a2)))

[[-4.83333333  3.33333333]
 [ 1.5        -1.        ]]


In [ ]:
from numpy.linalg import inv

In [ ]:
inv(a1.dot(a2))

array([[-4.83333333,  3.33333333],
       [ 1.5       , -1.        ]])

In [ ]:
np.identity(a1.shape[0])

array([[1., 0.],
       [0., 1.]])

- 레온티에프 역행렬

In [ ]:
np.linalg.inv(np.identity(A.shape[0]) - A)

array([[ 0.7  , -0.5  ],
       [-0.225,  0.125]])

## random sample

- 동일한 랜덤표본을 얻기 위해서는 numpy.random.seed(n) (예: n=1) 실행
    - seed()를 지정하지 않는 경우 파이썬은 현재 날짜-시간을 이용하여 seed() 지정

In [187]:
import numpy as np

In [188]:
rsn = np.random.randn(10)

In [189]:
rsn

array([-0.60895717, -0.82305526, -1.55377727,  1.14248269, -0.64340991,
        2.04169005, -0.43915868,  0.31501826, -0.86339047, -2.08904793])

In [190]:
rsi = np.random.randint(1, 10, 10)

In [191]:
rsi

array([8, 6, 3, 9, 5, 6, 6, 6, 2, 7])

In [192]:
rsu = np.random.uniform(-1, 1, 10)

In [193]:
rsu

array([-0.41078705, -0.50689984,  0.39877523,  0.80042766,  0.12287271,
       -0.94712016,  0.78548871,  0.30399505,  0.28601893, -0.34132105])

In [194]:
np.random.seed(1)
np.random.randn(3)

array([ 1.62434536, -0.61175641, -0.52817175])

In [195]:
np.random.seed(2)
np.random.randn(3)

array([-0.41675785, -0.05626683, -2.1361961 ])

In [196]:
np.random.seed(1)
np.random.randn(3)

array([ 1.62434536, -0.61175641, -0.52817175])

# 연습문제

- 아래 두 문제 가운데 한 문제를 선택



1.   아래 식을 참고하여 선형회귀 계수 추정량을 계산하는 함수를 작성하고, 선형회귀모형을 추정하시오


$y = X \beta + u$ with $u \sim norm(0, 1) / 2$

$y$는 $n \times 1$ 종속변수 벡터, $X$는 $n \times p$ 설명변수 매트릭스, $\beta$는 $p \times 1$ 계수 벡터, $u$는 $\times 1$ 비관측 요인 벡터
$x_{1,t}=1$,


$x_{2,t}=0.5 \times x_{2,t-1} + \varepsilon_2$ with $x_{2,0} = 1$ and $\varepsilon_2 \sim norm(0,1)$


$x_{3,t}=0.2 \times x_{3,t-1} + 2\varepsilon_3$ with $x_{3,0} = 2$ and $\varepsilon_3 \sim norm(0,1)$

$\beta = [1, 2, 3]$




2.   랜덤표본을 이용하여 원주율(np.pi) 근사값을 구하시오 (힌트: 가로, 세로 길이가 2인 정사각형에 내접한 원의 면적은 np.pi)