# 2. 파이썬 익숙해지기

# 주요 내용

### [주피터노트북](#notebook)

### [파이썬 기초](#python)

### [넘파이](#numpy)

#### 파이썬

In [1]:
pwd

'/Users/hyunchangyi/python2020'

In [4]:
ls

ECOS/           SSD/            pandas.ipynb*
FFC/            WIOT/           tutorial.ipynb*


In [5]:
cd ..

/Users/hyunchangyi


In [6]:
cd python2020

/Users/hyunchangyi/python2020


<a id='notebook'></a>

# 2.1 주피터노트북

셀 타입: 코드, 마크다운

셀 모드: 편집모드, 명령모드

## 주피터노트북 단축키

셀 잘라내기/복사하기

셀 붙이기

삭제

새로운 셀 삽입하기

셀 타입 전환

실행취소

단축키 확인

셀 병합

셀 분할

## 셀 실행

In [ ]:
시프트 + 엔터, 컨트롤 + 엔터

###### 마크다운 헤더 서식

<a id='python'></a>

# 2.2. 파이썬 이 것만 알아두자

- 자료형
- 문법
- 라이브러리

# 자료형

## 숫자, 참/거짓, 문자열

In [7]:
1

1

In [8]:
type(1)

int

In [9]:
type(1.0)

float

In [10]:
False, True

(False, True)

In [11]:
type(False)

bool

In [12]:
type('python')

str

In [13]:
type("python")

str

In [14]:
type('a')

str

In [15]:
type("p")

str

In [17]:
type('python'), type(.5)

(str, float)

In [18]:
a = 5
b = (a == 5)
c = 'KOR'
print(a, b, c)

5 True KOR


### 더하기

In [19]:
4 + 5

9

In [20]:
'KOR' + '15'

'KOR15'

In [21]:
'KOR' + 15

TypeError: can only concatenate str (not "int") to str

In [23]:
'KOR' + '_' + str(15)

'KOR_15'

In [24]:
type(str(15))

str

In [27]:
float(str(15))

15.0

In [28]:
4 + True

5

In [29]:
4 + False

4

In [30]:
4 * True

4

In [31]:
4 * False

0

In [33]:
int(True)

1

### 프린트 포맷

In [34]:
a = 2
b = 'two'
print(a, b)

2 two


In [35]:
print('{} is {}'.format(a, b))

2 is two


In [36]:
print('{0:} is {1:}'.format(a, b))

2 is two


In [37]:
print('{1:} is {0:.2f}'.format(a, b))

two is 2.00


In [38]:
print('{1:} is {0:,.2f}'.format(10000, b))

two is 10,000.00


문자열에서 공백이나 특정 문자 없애기

In [39]:
" abc ".lstrip()

'abc '

In [40]:
" abc ".rstrip()

' abc'

In [41]:
" abc ".strip()

'abc'

In [42]:
"abc".strip('a')

'bc'

## 리스트

### 리스트에 숫자 곱하기, 리스트 더하기

In [43]:
a = [1, 2, 3]
b = ['one', 'two', 'three']

In [44]:
type(a)

list

In [45]:
a * 2

[1, 2, 3, 1, 2, 3]

In [46]:
b * 2

['one', 'two', 'three', 'one', 'two', 'three']

In [47]:
a + b

[1, 2, 3, 'one', 'two', 'three']

In [48]:
a + 5

TypeError: can only concatenate list (not "int") to list

In [49]:
a + 'four'

TypeError: can only concatenate list (not "str") to list

list에 숫자, 문자열 하나를 더하는 연산이 정의되어 있지 않으므로 오류발생

In [50]:
a + [5]

[1, 2, 3, 5]

뒤에 다룰 넘파이 ndarray 자료형은 숫자형 자료 리스트처럼 생겼으나, 숫자 하나를 더할 수 있음

In [51]:
b.append('four')
print(b)

['one', 'two', 'three', 'four']


리스트에서 항목별로 숫자를 더하기 위해서는 list comprehension이나 for-loop 이용

In [52]:
[i + 1 for i in a]

[2, 3, 4]

In [53]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

리스트에 있는 문자열을 특정 기호로 연결

In [54]:
b

['one', 'two', 'three', 'four']

In [55]:
':'.join(b)

'one:two:three:four'

## 파이썬 인덱스는 0부터 시작!! 

In [56]:
a[0]

1

In [57]:
a[0:2]

[1, 2]

list의 마지막 항목은 -1 인덱스

In [58]:
a[-1]

3

In [59]:
a = ['KOR', 'USA', 'CHN']
print(a[0], a[-1], a[:2], a[-2:])

KOR CHN ['KOR', 'USA'] ['USA', 'CHN']


- 주피터노트북에서 긴 리스트는 세로로 표시되지만, %pprint 명령어로 옵션 변경 가능,
- print() 명령어를 사용하면, 긴 리스트도 가로로 표시

In [60]:
a * 4

['KOR',
 'USA',
 'CHN',
 'KOR',
 'USA',
 'CHN',
 'KOR',
 'USA',
 'CHN',
 'KOR',
 'USA',
 'CHN']

In [61]:
print(a * 4)

['KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN']


In [64]:
%pprint

Pretty printing has been turned ON


In [63]:
a * 4

['KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN']

- 문자열 리스트의 각 항목을 따옴표 없이 print()하기 위해 리스트이름 앞에 * 입력
- 각 항목을 특정 기호로 구분하기 위해 sep = '기호' 옵션을 지정

In [65]:
print(a)

['KOR', 'USA', 'CHN']


In [66]:
print(*a)

KOR USA CHN


In [67]:
print(*a, sep = ', ')

KOR, USA, CHN


## list comprehension

- 간편하게 리스트 내용을 편집

In [68]:
['KOR', 'USA', 'CHN'] - ['CHN', 'AUS']

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [69]:
[s for s in ['KOR', 'USA', 'CHN'] if s not in ['CHN', 'AUS']]

['KOR', 'USA']

#### set 함수 이용

In [70]:
set(['KOR', 'USA', 'CHN']), set(['CHN', 'AUS'])

({'CHN', 'KOR', 'USA'}, {'AUS', 'CHN'})

In [71]:
set(['KOR', 'USA', 'CHN']) - set(['CHN', 'AUS'])

{'KOR', 'USA'}

In [72]:
list(set(['KOR', 'USA', 'CHN']) - set(['CHN', 'AUS']))

['USA', 'KOR']

문자열 리스트에 항목별 문자열 더하기

In [73]:
[s + ':g' for s in ['KOR', 'USA', 'CHN']]

['KOR:g', 'USA:g', 'CHN:g']

## 출력셀 값 불러오기

In [74]:
_

['KOR:g', 'USA:g', 'CHN:g']

In [75]:
Out[72]

['USA', 'KOR']

In [76]:
_69

['KOR', 'USA']

# 딕셔너리

In [77]:
iso = {'US':'USA', 'KR':'KOR', 'JP':'JPN', 'CN':'CHN'}

In [78]:
kr_en = {'서울특별시':'SE', '경기도':'GG', '인청광역시':'IC'}

In [79]:
iso['US']

'USA'

In [80]:
iso['KR']

'KOR'

In [81]:
iso.keys()

dict_keys(['US', 'KR', 'JP', 'CN'])

In [82]:
iso.values()

dict_values(['USA', 'KOR', 'JPN', 'CHN'])

In [83]:
iso['AU'] = 'AUS'

In [84]:
iso

{'US': 'USA', 'KR': 'KOR', 'JP': 'JPN', 'CN': 'CHN', 'AU': 'AUS'}

dict, zip으로 딕셔너리 만들기

In [85]:
dict(zip(['한국', '미국', '일본'], ['KR', 'US', 'JP']))

{'한국': 'KR', '미국': 'US', '일본': 'JP'}

In [86]:
import pandas as pd
countries = pd.Series(['South Korea', 'United States'])
print(countries)

0      South Korea
1    United States
dtype: object


In [87]:
cdict = {'South Korea':'KR', 'United States':'US'}
countries.replace(cdict)

0    KR
1    US
dtype: object

### 터플

In [88]:
a, b, c = 5, 10, 15

In [89]:
print(a, b, c)

5 10 15


In [90]:
a, b = b, a
print(a, b)

10 5


# 연습문제

## list comprehension 이용

- 아래 국가명 리스트와 연도 리스트를 이용하여 국가명_연도 문자열을 생성하라
- 아래 리스트와 인덱스를 이용하여 일본과 중국에 대해서만 국가명_연도 문자열을 생성하라
- 딕셔너리를 이용하여 countries 리스트의 아시아 국가명을 'ASIA'로 변경하라(힌트: 딕셔너리의 get 함수 이용, dict.get())

In [92]:
countries = ['KOR', 'USA', 'JPN', 'CHN', 'AUS', 'MEX']
year = [17, 18, 19, 20]

- 아래 문자열 리스트에서 숫자로 이루어진 문자열만 선택하여 리스트를 생성하라

In [99]:
list1 = ['KOR', '한국', '15', "True", '1000']
list2 = ['KOR', '한국', '15', "True", '1000', '-5']

<a id='grammar'></a>

## 문법

- 파이썬에서 for loop, if 구문, 함수정의시 indentation(스페이스 4개) 이용. 
    - 주피터노트북에서 tab은 스페이스 4개를 입력
- 코드작성의 자유도가 낮은 대신, 가독성이 매우 높아짐

In [104]:
def sum_two_numbers(a, b):
    return a + b

In [105]:
sum_two_numbers(1, 2)

3

In [106]:
countries = ['KOR', 'USA', 'CHN']
for c in countries:
    if c == 'KOR':
        print(c, 'is my country.')
    else:
        print(c)

KOR is my country.
USA
CHN


### list comprehension과 for-loop 비교

In [107]:
[s for s in ['KOR', 'USA', 'CHN'] if s not in ['CHN','AUS']]

['KOR', 'USA']

In [108]:
clist = []
for c in ['KOR', 'USA', 'CHN']:
    if c not in ['CHN', 'AUS']:
        clist = clist + [c] # clist.append(c)
clist

['KOR', 'USA']

<a id='numpy'></a>

# 라이브러리

- numpy

In [109]:
import numpy
import numpy as np
print(numpy.sin(0), np.sin(0))

0.0 0.0


In [110]:
print(sin(0))

NameError: name 'sin' is not defined

In [111]:
print(np.pi)

3.141592653589793


### ndarray는 행(row)과 열(column) 보다 첫번째 차원, 두번째 차원, 세번째 차원 등으로 정의

- 필요한 경우 matrix 자료형을 사용할 수 있으나 활용도가 낮음
- ndarray자료형을 이용하여 일반적인 matrix연산을 모두 할 수 있음
- 2-dim ndarray에서 행(row)처럼 보이는 것은 첫번째 차원임

### 특정 열(두번째 차원)에 접근하기 위해서는 콜론(:)을 첫번째 인덱스 자리에 입력

In [117]:
a1 = np.array([[1,2 ,3], [2, 3, 4]])

In [118]:
a1[:, 0]

array([1, 2])

In [119]:
a1[0, :]

array([1, 2, 3])

### 통계량 계산

In [120]:
v = np.array([1, 2, 3])
print(v)

[1 2 3]


In [121]:
type(v)

numpy.ndarray

In [122]:
m = np.array([[1, 2], [3, 4]])
m

array([[1, 2],
       [3, 4]])

In [123]:
print(v.mean(), v.std(), v.max())

2.0 0.816496580927726 3


In [124]:
np.sin([0, np.pi / 2, np.pi])

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [125]:
a = np.array([[1, 2], [3, 4]])

In [126]:
a

array([[1, 2],
       [3, 4]])

In [127]:
a[0,0] = -1

In [128]:
a

array([[-1,  2],
       [ 3,  4]])

In [129]:
a[0] = 0
a

array([[0, 0],
       [3, 4]])

In [130]:
a[:, 1] = [5, 6]
print(a)

[[0 5]
 [3 6]]


In [131]:
v1 = np.array([1, 2, 3])
v2 = np.array([-1, 0, 1])

In [132]:
v1 + 1

array([2, 3, 4])

In [133]:
v1 * 2

array([2, 4, 6])

In [134]:
v1 ** 2

array([1, 4, 9])

In [135]:
np.log(v1)

array([0.        , 0.69314718, 1.09861229])

In [136]:
np.exp(v1)

array([ 2.71828183,  7.3890561 , 20.08553692])

### ndarray의 dim

In [137]:
v1.shape

(3,)

In [138]:
a2 = np.array([[1, 2], [1, 3], [1, 4]])

In [139]:
a2

array([[1, 2],
       [1, 3],
       [1, 4]])

In [140]:
a2.shape

(3, 2)

In [142]:
a1

array([[1, 2, 3],
       [2, 3, 4]])

In [143]:
a1 * a2

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

#### ndarray 간의 +, -, *, / 등 사칙연산은 elementwise이므로 모양이 서로 같아야함 

In [144]:
v1.shape, v2.shape

((3,), (3,))

In [145]:
v1 + v2

array([0, 2, 4])

In [146]:
v1 * v2

array([-1,  0,  3])

In [147]:
v1.dot(v2)

2

In [148]:
m

array([[1, 2],
       [3, 4]])

In [149]:
m.T

array([[1, 3],
       [2, 4]])

In [150]:
v = np.array([1, 0])
m.dot(v)

array([1, 3])

In [151]:
v.dot(m)

array([1, 2])

In [152]:
print('{} \n\n {}'.format(a1, a2.T))

[[1 2 3]
 [2 3 4]] 

 [[1 1 1]
 [2 3 4]]


In [153]:
print(a1 * a2.T)

[[ 1  2  3]
 [ 4  9 16]]


### ndarray 간의 matrix multiplication은 dot() 메소드를 이용

- numpy array로 생성된 객체는 ndarray 클래스의 메소드와 속성을 가짐
- transpose, dot product 등

In [154]:
a1.dot(a2)

array([[ 6, 20],
       [ 9, 29]])

In [155]:
np.dot(a1, a2)

array([[ 6, 20],
       [ 9, 29]])

In [156]:
A = np.dot(a1, a2)
print(A)

[[ 6 20]
 [ 9 29]]


### 역행렬은 linalg라는 하위 library의 inv() 함수 이용

In [157]:
print(np.linalg.inv(a1.dot(a2)))

[[-4.83333333  3.33333333]
 [ 1.5        -1.        ]]


In [158]:
from numpy.linalg import inv

In [160]:
inv(a1.dot(a2))

array([[-4.83333333,  3.33333333],
       [ 1.5       , -1.        ]])

In [161]:
np.identity(a1.shape[0])

array([[1., 0.],
       [0., 1.]])

### 레온티에프 역행렬

In [162]:
np.linalg.inv(np.identity(A.shape[0]) - A)

array([[ 0.7  , -0.5  ],
       [-0.225,  0.125]])

### 랜덤표본

In [163]:
import numpy as np

In [164]:
rsn = np.random.randn(10)

In [165]:
rsn

array([ 0.01037403,  0.07021107, -0.48301298,  0.82988532,  0.3194111 ,
        1.14279009,  0.54392704,  0.57766371,  1.22208553,  1.44162574])

In [166]:
rsi = np.random.randint(1, 10, 10)

In [167]:
rsi

array([6, 4, 9, 9, 4, 9, 7, 6, 2, 1])

In [168]:
rsu = np.random.uniform(-1, 1, 10)

In [169]:
rsu

array([ 0.88472335, -0.70020221, -0.65366842, -0.1916791 ,  0.08396382,
       -0.00458484, -0.34562471, -0.79913341, -0.14639673,  0.86682845])

# 연습문제

### for-loop, if-else 구문 이용

- 아래 국가명 리스트와 연도 리스트를 이용하여 국가명_연도 문자열을 생성하라

In [ ]:
countries = ['KOR', 'USA', 'JPN', 'CHN', 'AUS', 'MEX']
year = [17, 18, 19, 20]

- 아래 문자열 리스트에서 숫자로 이루어진 문자열만 선택하여 리스트를 생성하라

In [ ]:
list1 = ['KOR', '한국', '15', "True", '1000']

### 아래 식을 참고하여 선형회귀 계수 추정량을 계산하는 함수를 작성하고, 선형회귀모형을 추정하시오

$y = X \beta + u$ with $u \sim norm(0, 1) / 2$

$y$는 $n \times 1$ 종속변수 벡터, $X$는 $n \times p$ 설명변수 매트릭스, $\beta$는 $p \times 1$ 계수 벡터, $u$는 $\times 1$ 비관측 요인 벡터

$x_{1,t}=1$,

$x_{2,t}=0.5 \times x_{2,t-1} + \varepsilon_2$ with $x_{2,0} = 1$ and $\varepsilon_2 \sim norm(0,1)$


$x_{3,t}=0.2 \times x_{3,t-1} + 2\varepsilon_3$ with $x_{3,0} = 2$ and $\varepsilon_3 \sim norm(0,1)$

$\beta = [1, 2, 3]$

### 랜덤표본을 이용하여 원주율(np.pi) 근사값을 구하시오
##### (힌트: 가로, 세로 길이가 2인 정사각형에 내접한 원의 면적은 np.pi)